# Bootcamp Mode Toggle Workflow
name: "bootcamp-mode-toggle"
description: "Switch configuration between client delivery and bootcamp training modes"
author: "Agri-AI Design Lab"

config_source: "{project-root}/.bmad/custom/modules/agri-ai-design-lab/config.yaml"
output_folder: "{config_source}:output_folder"

instructions: "{project-root}/.bmad/custom/modules/agri-ai-design-lab/workflows/bootcamp-mode-toggle/instructions.md"
template: false
standalone: true
