// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/admin/init-db': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/init-db.post').default>>>>
    }
    '/api/admin/stats': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/stats.get').default>>>>
    }
    '/api/admin/system/roles': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/system/roles.get').default>>>>
    }
    '/api/admin/test-hub': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/test-hub.get').default>>>>
    }
    '/api/admin/users/:id/role': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/users/[id]/role.patch').default>>>>
    }
    '/api/admin/users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/users/index.get').default>>>>
    }
    '/api/ai/calendar': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ai/calendar.get').default>>>>
    }
    '/api/ai/chat': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ai/chat.post').default>>>>
    }
    '/api/ai/crops/search': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ai/crops/search.get').default>>>>
    }
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout.post').default>>>>
    }
    '/api/auth/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/me.get').default>>>>
    }
    '/api/auth/profile': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/profile.patch').default>>>>
    }
    '/api/auth/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/register.post').default>>>>
    }
    '/api/browser/generate-agriculture-report': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/browser/generate-agriculture-report.post').default>>>>
    }
    '/api/cache-demo/agriculture-stats': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cache-demo/agriculture-stats.get').default>>>>
    }
    '/api/vectorize/crops-search': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/vectorize/crops-search.post').default>>>>
    }
    '/api/_hub/analytics': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxthub/core/dist/runtime/server/api/_hub/analytics/index.put').default>>>>
    }
    '/api/_hub/blob/**:pathname': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxthub/core/dist/runtime/server/api/_hub/blob/[...pathname].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxthub/core/dist/runtime/server/api/_hub/blob/[...pathname].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxthub/core/dist/runtime/server/api/_hub/blob/[...pathname].put').default>>>>
    }
    '/api/_hub/blob/delete': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxthub/core/dist/runtime/server/api/_hub/blob/delete.post').default>>>>
    }
    '/api/_hub/blob/head/**:pathname': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxthub/core/dist/runtime/server/api/_hub/blob/head/[...pathname].get').default>>>>
    }
    '/api/_hub/blob': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxthub/core/dist/runtime/server/api/_hub/blob/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxthub/core/dist/runtime/server/api/_hub/blob/index.post').default>>>>
    }
    '/api/_hub/cache/**:key': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxthub/core/dist/runtime/server/api/_hub/cache/[...key].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxthub/core/dist/runtime/server/api/_hub/cache/[...key].get').default>>>>
      'options': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxthub/core/dist/runtime/server/api/_hub/cache/[...key].options').default>>>>
    }
    '/api/_hub/cache/batch-delete': {
      'options': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxthub/core/dist/runtime/server/api/_hub/cache/batch-delete.options').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxthub/core/dist/runtime/server/api/_hub/cache/batch-delete.post').default>>>>
    }
    '/api/_hub/cache/clear/**:base': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxthub/core/dist/runtime/server/api/_hub/cache/clear/[...base].delete').default>>>>
      'options': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxthub/core/dist/runtime/server/api/_hub/cache/clear/[...base].options').default>>>>
    }
    '/api/_hub/cache': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxthub/core/dist/runtime/server/api/_hub/cache/index.get').default>>>>
    }
    '/api/_hub/database/:command': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxthub/core/dist/runtime/server/api/_hub/database/[command].post').default>>>>
    }
    '/api/_hub/database/query': {
      'options': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxthub/core/dist/runtime/server/api/_hub/database/query.options').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxthub/core/dist/runtime/server/api/_hub/database/query.post').default>>>>
    }
    '/api/_hub': {
      'head': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxthub/core/dist/runtime/server/api/_hub/index.head').default>>>>
    }
    '/api/_hub/kv/**:path': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxthub/core/dist/runtime/server/api/_hub/kv/[...path]').default>>>>
    }
    '/api/_hub/manifest': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxthub/core/dist/runtime/server/api/_hub/manifest.get').default>>>>
    }
    '/api/_hub/openapi': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxthub/core/dist/runtime/server/api/_hub/openapi.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/_openapi.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nitropack/dist/runtime/internal/routes/openapi').default>>>>
    }
    '/_scalar': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nitropack/dist/runtime/internal/routes/scalar').default>>>>
    }
    '/_swagger': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nitropack/dist/runtime/internal/routes/swagger').default>>>>
    }
  }
}
export {}