// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/admin/init-db': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/init-db.post').default>>>>
    }
    '/api/admin/stats': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/stats.get').default>>>>
    }
    '/api/admin/system/roles': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/system/roles.get').default>>>>
    }
    '/api/admin/test-hub': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/test-hub.get').default>>>>
    }
    '/api/admin/users/:id/role': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/users/[id]/role.patch').default>>>>
    }
    '/api/admin/users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/users/index.get').default>>>>
    }
    '/api/ai/calendar': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ai/calendar.get').default>>>>
    }
    '/api/ai/chat': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ai/chat.post').default>>>>
    }
    '/api/ai/crops/search': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ai/crops/search.get').default>>>>
    }
    '/api/ai/n8n-query': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ai/n8n-query.post').default>>>>
    }
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout.post').default>>>>
    }
    '/api/auth/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/me.get').default>>>>
    }
    '/api/auth/profile': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/profile.patch').default>>>>
    }
    '/api/auth/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/register.post').default>>>>
    }
    '/api/browser/generate-agriculture-report': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/browser/generate-agriculture-report.post').default>>>>
    }
    '/api/cache-demo/agriculture-stats': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cache-demo/agriculture-stats.get').default>>>>
    }
    '/api/n8n/content/all': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/n8n/content/all.get').default>>>>
    }
    '/api/n8n/users/farmers': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/n8n/users/farmers.get').default>>>>
    }
    '/api/vectorize/crops-search': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/vectorize/crops-search.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}