# This file controls the behavior of the Supabase CLI
# Refer to the docs for detailed guidance: https://supabase.com/docs/reference/cli/config

# The project ID can be found in your Supabase dashboard URL:
# https://app.supabase.com/project/{project-id}
project_id = "rxsnczjqcrcojspdahug"

[api]
# Port for the API URL (defaults to 54321)
port = 54321
# Schemas to expose in your API
schemas = ["public", "storage", "auth"]
# Extra schemas to add to the search_path of every request
extra_search_path = ["public", "extensions"]
# Maximum rows returns from a view, table, or stored procedure (defaults to 1000)
max_rows = 1000

[db]
# Port for the database (defaults to 54322)
port = 54322
# Database major version (defaults to 15)
major_version = 15

[studio]
# Port for Supabase Studio (defaults to 54323)
port = 54323

[auth]
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:8080"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://localhost:8080"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604,800 (1 week).
jwt_expiry = 3600
# Allow/disallow new user signups to your project.
enable_signup = true

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email
# addresses. If disabled, only the new email is required to confirm.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = true