// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/9/2025, 12:08:17 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/fefe/Documents/Fataplus Project /Fataplus/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/fefe/Documents/Fataplus Project /Fataplus/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/fefe/Documents/Fataplus Project /Fataplus/shared/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/fefe/Documents/Fataplus Project /Fataplus/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/fefe/Documents/Fataplus Project /Fataplus/plugins/**/*.{js,ts,mjs}","/Users/fefe/Documents/Fataplus Project /Fataplus/composables/**/*.{js,ts,mjs}","/Users/fefe/Documents/Fataplus Project /Fataplus/utils/**/*.{js,ts,mjs}","/Users/fefe/Documents/Fataplus Project /Fataplus/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/fefe/Documents/Fataplus Project /Fataplus/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/fefe/Documents/Fataplus Project /Fataplus/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/fefe/Documents/Fataplus Project /Fataplus/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;