// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/25/2025, 12:49:17 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/fefe/Documents/Fataplus/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/fefe/Documents/Fataplus/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/fefe/Documents/Fataplus/shared/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/fefe/Documents/Fataplus/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/fefe/Documents/Fataplus/plugins/**/*.{js,ts,mjs}","/Users/fefe/Documents/Fataplus/composables/**/*.{js,ts,mjs}","/Users/fefe/Documents/Fataplus/composables/**/**/*.{js,ts,mjs}","/Users/fefe/Documents/Fataplus/utils/**/*.{js,ts,mjs}","/Users/fefe/Documents/Fataplus/utils/**/**/*.{js,ts,mjs}","/Users/fefe/Documents/Fataplus/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/fefe/Documents/Fataplus/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/fefe/Documents/Fataplus/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/fefe/Documents/Fataplus/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;