// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/24/2025, 10:40:56 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/fefe/Documents/Fataplus/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/fefe/Documents/Fataplus/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/fefe/Documents/Fataplus/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/fefe/Documents/Fataplus/plugins/**/*.{js,ts,mjs}","/Users/fefe/Documents/Fataplus/stores/**/*.{js,ts,mjs}","/Users/fefe/Documents/Fataplus/composables/**/*.{js,ts,mjs}","/Users/fefe/Documents/Fataplus/utils/**/*.{js,ts,mjs}","/Users/fefe/Documents/Fataplus/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/fefe/Documents/Fataplus/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/fefe/Documents/Fataplus/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/fefe/Documents/Fataplus/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;