# Data Readiness Audit Workflow
name: "data-readiness-audit"
description: "Assess datasets, governance, and infrastructure readiness for AI concepts"
author: "Agri-AI Design Lab"

config_source: "{project-root}/.bmad/custom/modules/agri-ai-design-lab/config.yaml"
output_folder: "{config_source}:output_folder"

instructions: "{project-root}/.bmad/custom/modules/agri-ai-design-lab/workflows/data-readiness-audit/instructions.md"
template: "{project-root}/.bmad/custom/modules/agri-ai-design-lab/workflows/data-readiness-audit/template.md"
standalone: true
