# AI Service Blueprint Workflow
name: "ai-service-blueprint"
description: "Produce AI-enabled service blueprint combining digital and field operations"
author: "Agri-AI Design Lab"

config_source: "{project-root}/.bmad/custom/modules/agri-ai-design-lab/config.yaml"
output_folder: "{config_source}:output_folder"

instructions: "{project-root}/.bmad/custom/modules/agri-ai-design-lab/workflows/ai-service-blueprint/instructions.md"
template: "{project-root}/.bmad/custom/modules/agri-ai-design-lab/workflows/ai-service-blueprint/template.md"
standalone: true
